[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name             forward
    Listen           0.0.0.0
    Port             24224
    Tag              docker

[OUTPUT]
    Name             loki
    Match            *
    Host             loki
    Port             3100
    Labels           job=fluentbit, container_name=kodekloud-record-store-api
    Line_Format      json