[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name        tail
    Path        /var/log/containers/kodekloud-record-store-api*.log
    Parser      docker
    Tag         kube.kodekloud-record-store-api
    Mem_Buf_Limit 5MB

[INPUT]
    Name        tail
    Path        /var/log/containers/kodekloud-record-store-worker*.log
    Parser      docker
    Tag         kube.kodekloud-record-store-worker
    Mem_Buf_Limit 5MB

[FILTER]
    Name        kubernetes
    Match       kube.*
    Merge_Log   On
    Keep_Log    Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude On

[OUTPUT]
    Name        loki
    Match       *
    Host        loki
    Port        3100
    Labels      job=fluentbit
    Label_Keys  $tag