   groups:
   - name: example
     rules:
     - alert: HighErrorRate
       expr: rate(http_request_errors_total[5m]) > 0.05
       for: 5m
       labels:
         severity: critical
       annotations:
         summary: "High error rate detected"
         description: "The error rate is above 5% for the last 5 minutes."

     - alert: LongRequestDuration
       expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
       for: 5m
       labels:
         severity: warning
       annotations:
         summary: "Long request duration detected"
         description: "95th percentile request duration is above 1 second for the last 5 minutes."